import type { Locale } from "./locales";
import { CASINOS, GAMES, SPORTS } from "./strategy-data";

/**
 * Keywords for search: all types in all 20 languages.
 * - Casino + game + strategy/predictor (e.g. "Stake mines strategy" → "Stake マインズ 戦略" for ja).
 * - Sport type (betting, match prediction) in each locale.
 * - Game type (mines, crash, dice, blackjack, etc.) + strategy/predictor/tips in each locale.
 * - LOCALE_KEYWORDS = base phrases per language; LOCALE_STEMS = words to build "X strategy", "X predictor"; getMetaKeywords/getSportKeywords use both so every page gets keywords in its language.
 */

/** Common human typing errors / misspellings – SEO rank on typo searches (Google autocomplete-style) */
const TYPO_KEYWORDS = [
  "stake stratgy",
  "stake stratagy",
  "stake mines preditor",
  "stake crash predicter",
  "roobet stratgy",
  "roobet predicter",
  "stak casino",
  "roobt",
  "1xbet stratgy",
  "rollbit preditor",
  "bc game stratgy",
  "bustabit preditor",
  "mines stratgy",
  "dice stratgy",
  "crash preditor",
  "blackjack stratgy",
  "plinko stratgy",
  "limbo preditor",
  "aviator preditor",
  "crypto casino stratgy",
  "sports betting preditor",
  "match predicion",
  "betting tips stratgy",
  "stake bonus code",
  "roobet bonus",
  "crypto casino bonous",
  "no depost bonus",
  "stratagy gamba",
  "predicter 2026",
  "casino stratagy",
  "stake vpn",
  "roobet vpn",
  "stake bonu",
  "roobet bonu",
  "no depost",
  "withdrwal casino",
  "stake legal",
  "roobet legal",
  "stake alternatve",
  "roobet alternatve",
  "crypto casiono",
  "stake promoo",
  "roobet welcom bonus",
  "free spin crypto",
  "stake withdrwal",
  "roobet no depost",
  "vpn for stake",
  "vpn for roobet",
  "stake mines predicion",
  "crash predicter",
  "rolbit",
  "bcgame",
  "bustabit preditor",
  "aviater",
  "spaceman stratgy",
  "jetx preditor",
  "crypto casio",
  "sport betting preditor",
  "bonus code stake",
  "bonus code roobet",
  "no deposit bonu",
  "instant withdrwal",
  "stake vs roobet",
  "dice stratgy",
  "dice preditor",
  "stake dice stratgy",
  "roobet dice preditor",
  "football predicion",
  "soccer predicion",
  "basketball preditor",
  "tennis predicion",
  "ufc preditor",
  "cricket predicion",
  "sport predicion",
  "match predicion today",
  "football beting",
  "soccer beting tips",
  "dice calculater",
  "stake dice calculater",
  "keno stratgy",
  "roulette stratgy",
  "baccarat stratgy",
  "slots stratgy",
  "hilo preditor",
  "spaceman stratgy",
  "jetx stratgy",
  "plinko preditor",
  "limbo stratgy",
  "roobet mines preditor",
  "stake crash stratgy",
  "crypto casiono bonus",
  "sport prediccion",
  "hacksaw stratgy",
  "pragmatic stratgy",
  "max win preditor",
  "download stratgy tool",
  "download preditor",
];

/** Top searched casino/gambling keywords – English base, 2026-relevant + long-tail */
const EN_BASE = [
  "Stake mines strategy",
  "Stake crash predictor",
  "Roobet strategy",
  "Roobet crash predictor",
  "1xbet strategy",
  "Rollbit mines",
  "BC.Game crash",
  "Bustabit predictor",
  "crypto casino strategy",
  "Stake blackjack strategy",
  "Roobet mines predictor",
  "crash game strategy",
  "mines game predictor",
  "dice strategy crypto",
  "plinko strategy",
  "limbo predictor",
  "aviator predictor",
  "sports betting tips",
  "match prediction",
  "betting strategy",
  "casino tips",
  "download betting tools",
  "Stake sports betting",
  "Roobet sports",
  "1xbet sports prediction",
  "Stake bonus code",
  "Roobet welcome bonus",
  "no deposit bonus crypto casino",
  "crypto casino bonus",
  "Stake promo code",
  "casino Bitcoin deposit",
  "crypto casino withdrawal",
  "RTP casino",
  "provably fair",
  "house edge",
  "live casino crypto",
  "mobile casino",
  "best crypto casino",
  "Stake vs Roobet",
  "casino withdrawal time",
  "VPN for casino",
  "Stake VPN",
  "Roobet VPN",
  "casino VPN",
  "Roobet alternative",
  "Stake alternative",
  "best Stake alternative",
  "instant withdrawal casino",
  "is Stake legal",
  "is Roobet legal",
  "Spaceman game",
  "Aviator game",
  "Crash X",
  "Sugar Rush casino",
  "JetX",
  "best crypto casino 2026",
  "Stake mines predictor 2026",
  "crash predictor tool",
  "mines strategy tips",
  "crypto casino predictor",
  "sports match prediction tool",
  "betting strategy 2026",
  "Rollbit crash strategy",
  "BC.Game mines",
  "1xbet crash predictor",
  "free betting tools download",
  "Strategy Gamba",
];

/** Top searched: VPN, bonus, legal, alternative, withdrawal – human search intent */
const EN_EXTRA = [
  "Stake VPN",
  "Roobet VPN",
  "VPN for Stake",
  "VPN for Roobet",
  "casino VPN 2026",
  "best VPN for crypto casino",
  "Stake no VPN",
  "Roobet access VPN",
  "Stake bonus code 2026",
  "Roobet welcome bonus 2026",
  "no deposit bonus crypto 2026",
  "crypto casino no deposit",
  "free spins crypto casino",
  "Stake promo code",
  "Roobet promo code",
  "is Stake legal",
  "is Roobet legal",
  "Stake legal countries",
  "Roobet legal USA",
  "Stake alternative",
  "Roobet alternative",
  "sites like Stake",
  "sites like Roobet",
  "best Stake alternative 2026",
  "instant withdrawal crypto casino",
  "fast withdrawal casino",
  "crypto casino withdrawal time",
  "Bitcoin casino no KYC",
  "Stake withdrawal",
  "Roobet withdrawal",
  "casino bonus no deposit",
  "welcome bonus no deposit",
  "free bonus crypto casino",
  "Stake free bonus",
  "Roobet free spins",
  "crash game predictor",
  "mines predictor tool",
  "sports prediction today",
  "betting tips today",
];

/** Dice – heavy coverage: strategy, predictor, Stake/Roobet, long-tail + short for fast ranking */
const EN_DICE = [
  "dice strategy",
  "Stake dice",
  "Roobet dice",
  "dice game strategy",
  "dice predictor",
  "dice betting strategy",
  "crypto dice",
  "dice game crypto",
  "Stake dice strategy",
  "Roobet dice strategy",
  "dice calculator",
  "dice odds",
  "dice 2x strategy",
  "dice multiplier",
  "high risk dice",
  "low risk dice",
  "dice provably fair",
  "dice bot",
  "dice strategy 2026",
  "Rollbit dice",
  "BC.Game dice",
  "dice game tips",
  "best dice strategy",
  "dice win strategy",
  "dice martingale",
  "dice double",
  "Stake dice predictor",
  "dice roll strategy",
  "crypto dice game",
  "dice strategy reddit",
  "dice gambling strategy",
  "online dice strategy",
  "dice game predictor",
  "TrustDice",
  "dice 50 50",
  "dice 90% win",
  "dice high multiplier",
  "dice low house edge",
  "1xbet dice",
  "dice crash",
  "dice and mines",
  "dice plinko strategy",
];

/** All sports – small + big keywords for every sport type (betting, prediction, tips, strategy) */
const EN_SPORTS_ALL = [
  "football betting",
  "football prediction",
  "football betting tips",
  "soccer betting",
  "soccer prediction",
  "soccer match prediction",
  "basketball betting",
  "basketball prediction",
  "basketball tips",
  "tennis betting",
  "tennis prediction",
  "tennis match prediction",
  "cricket betting",
  "cricket prediction",
  "cricket tips",
  "esports betting",
  "esports prediction",
  "UFC betting",
  "UFC prediction",
  "UFC tips",
  "boxing betting",
  "boxing prediction",
  "MMA betting",
  "MMA prediction",
  "horse racing betting",
  "horse racing tips",
  "American football betting",
  "NFL betting",
  "NFL prediction",
  "ice hockey betting",
  "hockey betting",
  "hockey prediction",
  "baseball betting",
  "baseball prediction",
  "MLB betting",
  "CSGO betting",
  "CSGO prediction",
  "Dota betting",
  "Dota 2 prediction",
  "League of Legends betting",
  "LoL prediction",
  "football match prediction today",
  "soccer tips today",
  "basketball betting strategy",
  "tennis betting tips",
  "cricket match prediction",
  "UFC fight prediction",
  "boxing match prediction",
  "MMA fight tips",
  "horse racing prediction today",
  "NFL betting tips",
  "hockey betting strategy",
  "baseball betting tips",
  "esports match prediction",
  "Stake football",
  "Stake soccer",
  "Roobet sports betting",
  "1xbet football",
  "sports prediction app",
  "match prediction today",
  "betting tips football",
  "betting tips soccer",
  "betting tips basketball",
  "betting tips tennis",
  "betting tips cricket",
  "betting tips UFC",
  "rugby betting",
  "rugby prediction",
  "golf betting",
  "golf prediction",
  "volleyball betting",
  "F1 betting",
  "Formula 1 prediction",
  "snooker betting",
  "darts betting",
  "darts prediction",
  "table tennis betting",
  "handball betting",
  "Olympics betting",
  "NBA betting",
  "NBA prediction",
  "Champions League betting",
  "Premier League prediction",
  "World Cup betting",
  "download sports prediction tool",
  "sports betting strategy 2026",
  "live betting tips",
  "in-play betting",
  "accumulator tips",
  "parlay betting strategy",
  "over under betting",
  "both teams to score prediction",
  "correct score prediction",
];

/** All other games – keno, roulette, blackjack, plinko, limbo, baccarat, slots, wheel, JetX, Spaceman, Aviator, etc. */
const EN_GAMES_OTHER = [
  "keno strategy",
  "keno predictor",
  "keno tips",
  "roulette strategy",
  "roulette predictor",
  "crypto roulette",
  "blackjack strategy",
  "blackjack tips",
  "Stake blackjack",
  "Roobet blackjack",
  "poker strategy",
  "crypto poker",
  "HiLo strategy",
  "HiLo predictor",
  "Stake HiLo",
  "plinko strategy",
  "plinko predictor",
  "plinko tips",
  "limbo strategy",
  "limbo predictor",
  "limbo multiplier",
  "baccarat strategy",
  "baccarat tips",
  "slots strategy",
  "crypto slots",
  "wheel strategy",
  "Stake wheel",
  "JetX strategy",
  "JetX predictor",
  "JetX game",
  "Spaceman strategy",
  "Spaceman predictor",
  "Aviator strategy",
  "Aviator predictor",
  "Aviator game tips",
  "Crash X strategy",
  "Sugar Rush strategy",
  "Dog House slots",
  "mines strategy",
  "mines predictor",
  "Stake mines",
  "Roobet mines",
  "crash strategy",
  "crash predictor",
  "Stake crash",
  "Bustabit strategy",
  "Rollbit strategy",
  "BC.Game strategy",
  "provably fair games",
  "RTP games",
  "best crash game 2026",
  "best mines game",
];

/** Guides & topics – RTP, provably fair, bonus, VPN, legal, withdrawal, mobile, live, responsible */
const EN_GUIDES = [
  "RTP casino",
  "RTP meaning",
  "house edge casino",
  "provably fair casino",
  "provably fair explained",
  "crypto casino deposit",
  "Bitcoin casino deposit",
  "bonus codes 2026",
  "no deposit bonus",
  "welcome bonus crypto",
  "responsible gambling",
  "responsible gambling tips",
  "mobile casino crypto",
  "mobile betting",
  "live casino crypto",
  "live dealer crypto",
  "VPN for Stake",
  "VPN for Roobet",
  "Stake alternative 2026",
  "Roobet alternative 2026",
  "instant withdrawal",
  "fast withdrawal crypto",
  "is Stake legal",
  "is Roobet legal",
  "Stake legal countries",
  "best crash game",
  "Strategy Gamba",
  "gamba strategy",
  "casino guide 2026",
];

/** Providers – Hacksaw Gaming, Pragmatic Play, strategy, best games, max win (all link to download our soft) */
const EN_PROVIDERS = [
  "Hacksaw Gaming",
  "Hacksaw Gaming slots",
  "Hacksaw strategy",
  "Hacksaw slots strategy",
  "best Hacksaw games",
  "Hacksaw max win",
  "Hacksaw casino",
  "Pragmatic Play",
  "Pragmatic Play slots",
  "Pragmatic Play strategy",
  "Pragmatic slots strategy",
  "best Pragmatic Play games",
  "Pragmatic max win",
  "Pragmatic casino",
  "Hacksaw vs Pragmatic",
  "Stake Hacksaw",
  "Stake Pragmatic Play",
  "crypto casino Hacksaw",
  "crypto casino Pragmatic",
  "slot strategy 2026",
  "provider strategy",
  "best slot providers",
  "Nolimit City strategy",
  "Push Gaming strategy",
  "Big Time Gaming slots",
  "NetEnt strategy",
  "Play'n GO slots",
  "Evolution Gaming",
  "live casino providers",
];

/** Best win / biggest win / max win – high-intent phrases, all lead to download our software */
const EN_BEST_WIN = [
  "best win casino",
  "biggest win casino",
  "max win",
  "max win strategy",
  "how to get max win",
  "casino biggest win",
  "how to win big casino",
  "best win strategy",
  "biggest win strategy",
  "slot max win",
  "crash max win",
  "mines max win",
  "dice max win",
  "Stake max win",
  "Roobet biggest win",
  "best win crypto casino",
  "big win strategy",
  "maximum win casino",
  "highest win strategy",
  "mega win casino",
  "jackpot strategy",
  "how to win more casino",
  "improve win chance",
  "download strategy tool win",
  "prediction tool best win",
  "strategy software biggest win",
];

/** Download our software – all pages link to download; keywords for ranking */
const EN_DOWNLOAD = [
  "download our software",
  "download strategy tool",
  "download predictor",
  "download betting tools",
  "free download betting software",
  "download casino strategy tool",
  "download mines predictor",
  "download crash predictor",
  "download sports prediction tool",
  "strategy tool download",
  "predictor software download",
  "betting tools free download",
  "download Strategy Gamba",
  "get strategy software",
  "free strategy tool download",
  "download full toolset",
  "casino predictor download",
  "download and win",
  "toolset download crypto casino",
];

/** Per-locale word stems – to build "Casino strategy", "Game predictor", "Sport betting" etc. in that language */
const LOCALE_STEMS: Record<
  Locale,
  { strategy: string; predictor: string; tips: string; betting: string; matchPrediction: string }
> = {
  en: { strategy: "strategy", predictor: "predictor", tips: "tips", betting: "betting", matchPrediction: "match prediction" },
  zh: { strategy: "策略", predictor: "预测", tips: "技巧", betting: "投注", matchPrediction: "比赛预测" },
  es: { strategy: "estrategia", predictor: "predictor", tips: "consejos", betting: "apuestas", matchPrediction: "predicción partidos" },
  hi: { strategy: "रणनीति", predictor: "भविष्यवाणी", tips: "टिप्स", betting: "बेटिंग", matchPrediction: "मैच भविष्यवाणी" },
  ar: { strategy: "استراتيجية", predictor: "متنبئ", tips: "نصائح", betting: "مراهنات", matchPrediction: "تنبؤ المباريات" },
  pt: { strategy: "estratégia", predictor: "predictor", tips: "dicas", betting: "apostas", matchPrediction: "previsão jogos" },
  ru: { strategy: "стратегия", predictor: "предиктор", tips: "советы", betting: "ставки", matchPrediction: "прогноз матчей" },
  ja: { strategy: "戦略", predictor: "予測", tips: "ヒント", betting: "ベッティング", matchPrediction: "試合予測" },
  de: { strategy: "Strategie", predictor: "Predictor", tips: "Tipps", betting: "Wetten", matchPrediction: "Spielvorhersage" },
  fr: { strategy: "stratégie", predictor: "prédicteur", tips: "conseils", betting: "paris", matchPrediction: "prédiction match" },
  ko: { strategy: "전략", predictor: "예측", tips: "팁", betting: "베팅", matchPrediction: "경기 예측" },
  tr: { strategy: "strateji", predictor: "tahminci", tips: "ipuçları", betting: "bahisler", matchPrediction: "maç tahmini" },
  vi: { strategy: "chiến lược", predictor: "dự đoán", tips: "mẹo", betting: "cá cược", matchPrediction: "dự đoán trận" },
  it: { strategy: "strategia", predictor: "predictor", tips: "consigli", betting: "scommesse", matchPrediction: "previsione partite" },
  nl: { strategy: "strategie", predictor: "predictor", tips: "tips", betting: "weddenschappen", matchPrediction: "wedstrijdvoorspelling" },
  pl: { strategy: "strategia", predictor: "predyktor", tips: "wskazówki", betting: "zakłady", matchPrediction: "predykcja meczu" },
  id: { strategy: "strategi", predictor: "prediktor", tips: "tips", betting: "taruhan", matchPrediction: "prediksi pertandingan" },
  th: { strategy: "กลยุทธ์", predictor: "ทำนาย", tips: "เคล็ดลับ", betting: "การเดิมพัน", matchPrediction: "ทำนายแมตช์" },
  bn: { strategy: "কৌশল", predictor: "ভবিষ্যদ্বাণী", tips: "টিপস", betting: "বেটিং", matchPrediction: "ম্যাচ ভবিষ্যদ্বাণী" },
  ms: { strategy: "strategi", predictor: "peramal", tips: "tips", betting: "pertaruhan", matchPrediction: "ramalan perlawanan" },
};

/** Per-locale extra: VPN, bonus, no deposit, legal, alternative, withdrawal – top searched in that language */
const LOCALE_EXTRA: Record<Locale, string[]> = {
  en: ["Stake VPN", "Roobet VPN", "casino VPN", "no deposit bonus", "welcome bonus", "is Stake legal", "Stake alternative", "instant withdrawal", "free spins crypto", "promo code casino"],
  zh: ["Stake VPN", "Roobet VPN", "赌场VPN", "无存款奖金", "欢迎奖金", "Stake合法", "Stake替代", "即时提款", "免费旋转", "促销码"],
  es: ["Stake VPN", "Roobet VPN", "VPN casino", "bono sin depósito", "bono bienvenida", "Stake legal", "alternativa Stake", "retiro instantáneo", "giros gratis", "código promocional"],
  hi: ["Stake VPN", "Roobet VPN", "कैसीनो VPN", "नो डिपॉजिट बोनस", "वेलकम बोनस", "Stake कानूनी", "Stake विकल्प", "तुरंत निकासी", "मुफ्त स्पिन", "प्रोमो कोड"],
  ar: ["Stake VPN", "Roobet VPN", "VPN كازينو", "بونص بدون إيداع", "بونص ترحيب", "Stake قانوني", "بديل Stake", "سحب فوري", "دورات مجانية", "كود ترويجي"],
  pt: ["Stake VPN", "Roobet VPN", "VPN casino", "bónus sem depósito", "bónus boas-vindas", "Stake legal", "alternativa Stake", "levantamento instantâneo", "giros grátis", "código promocional"],
  ru: ["Stake VPN", "Roobet VPN", "VPN казино", "бонус без депозита", "приветственный бонус", "Stake легально", "альтернатива Stake", "мгновенный вывод", "бесплатные вращения", "промокод"],
  ja: ["Stake VPN", "Roobet VPN", "カジノVPN", "ノーデポボーナス", "ウェルカムボーナス", "Stake合法", "Stake代替", "即時出金", "フリースピン", "プロモコード"],
  de: ["Stake VPN", "Roobet VPN", "Casino VPN", "Bonus ohne Einzahlung", "Willkommensbonus", "Stake legal", "Stake Alternative", "Sofortauszahlung", "Freispiele", "Aktionscode"],
  fr: ["Stake VPN", "Roobet VPN", "VPN casino", "bonus sans dépôt", "bonus bienvenue", "Stake légal", "alternative Stake", "retrait instantané", "tours gratuits", "code promo"],
  ko: ["Stake VPN", "Roobet VPN", "카지노 VPN", "노디포 보너스", "웰컴 보너스", "Stake 합법", "Stake 대안", "즉시 출금", "무료 스핀", "프로모 코드"],
  tr: ["Stake VPN", "Roobet VPN", "casino VPN", "depositsız bonus", "hoş geldin bonusu", "Stake yasal", "Stake alternatifi", "anında çekim", "ücretsiz dönüş", "promosyon kodu"],
  vi: ["Stake VPN", "Roobet VPN", "VPN casino", "thưởng không nạp", "thưởng chào mừng", "Stake hợp pháp", "thay thế Stake", "rút tiền tức thì", "vòng quay miễn phí", "mã khuyến mãi"],
  it: ["Stake VPN", "Roobet VPN", "VPN casino", "bonus senza deposito", "bonus benvenuto", "Stake legale", "alternativa Stake", "prelievo istantaneo", "giri gratuiti", "codice promozionale"],
  nl: ["Stake VPN", "Roobet VPN", "casino VPN", "bonus zonder storting", "welkomstbonus", "Stake legaal", "Stake alternatief", "direct opname", "gratis spins", "promocode"],
  pl: ["Stake VPN", "Roobet VPN", "VPN kasyno", "bonus bez depozytu", "bonus powitalny", "Stake legalny", "alternatywa Stake", "natychmiastowa wypłata", "darmowe spiny", "kod promocyjny"],
  id: ["Stake VPN", "Roobet VPN", "VPN casino", "bonus tanpa deposit", "bonus selamat datang", "Stake legal", "alternatif Stake", "penarikan instan", "putaran gratis", "kode promosi"],
  th: ["Stake VPN", "Roobet VPN", "VPN คาสิโน", "โบนัสไม่ต้องฝาก", "โบนัสต้อนรับ", "Stake ถูกกฎหมาย", "ทางเลือก Stake", "ถอนทันที", "ฟรีสปิน", "รหัสโปรโมชั่น"],
  bn: ["Stake VPN", "Roobet VPN", "ক্যাসিনো VPN", "নো ডিপোজিট বোনাস", "স্বাগত বোনাস", "Stake আইনি", "Stake বিকল্প", "তাৎক্ষণিক উত্তোলন", "বিনামূল্যে স্পিন", "প্রমো কোড"],
  ms: ["Stake VPN", "Roobet VPN", "VPN kasino", "bonus tanpa deposit", "bonus selamat datang", "Stake sah", "alternatif Stake", "pengeluaran segera", "putaran percuma", "kod promosi"],
};

/** Native phrases per locale – dice, mines, crash, football, keno, roulette, etc. in that language (Google perfection) */
const LOCALE_NATIVE: Record<Locale, string[]> = {
  en: ["dice strategy", "mines strategy", "crash predictor", "football betting", "keno tips", "roulette strategy", "blackjack tips", "plinko strategy", "aviator predictor"],
  zh: ["骰子策略", "扫雷策略", "crash预测", "足球投注", "基诺技巧", "轮盘策略", "二十一点技巧", "plinko策略", "飞行器预测"],
  es: ["estrategia dados", "estrategia minas", "predictor crash", "apuestas fútbol", "keno consejos", "estrategia ruleta", "blackjack consejos", "estrategia plinko", "predictor aviator"],
  hi: ["पासा रणनीति", "माइन्स रणनीति", "क्रैश भविष्यवाणी", "फुटबॉल बेटिंग", "केनो टिप्स", "रूलेट रणनीति", "ब्लैकजैक टिप्स", "प्लिंको रणनीति", "एविएटर भविष्यवाणी"],
  ar: ["استراتيجية النرد", "استراتيجية المناجم", "متنبئ كراش", "مراهنات كرة القدم", "نصائح كينو", "استراتيجية الروليت", "نصائح بلاك جاك", "استراتيجية بلينكو", "متنبئ أفياتور"],
  pt: ["estratégia dados", "estratégia minas", "predictor crash", "apostas futebol", "keno dicas", "estratégia roleta", "blackjack dicas", "estratégia plinko", "predictor aviator"],
  ru: ["стратегия кости", "стратегия мин", "предиктор краш", "ставки футбол", "советы кено", "стратегия рулетка", "советы блэкджек", "стратегия плинко", "предиктор авиатор"],
  ja: ["ダイス戦略", "マインズ戦略", "クラッシュ予測", "サッカー betting", "キノヒント", "ルーレット戦略", "ブラックジャックヒント", "plinko戦略", "アビエーター予測"],
  de: ["Würfel Strategie", "Minen Strategie", "Crash Predictor", "Fußball Wetten", "Keno Tipps", "Roulette Strategie", "Blackjack Tipps", "Plinko Strategie", "Aviator Predictor"],
  fr: ["stratégie dés", "stratégie mines", "prédicteur crash", "paris football", "keno conseils", "stratégie roulette", "blackjack conseils", "stratégie plinko", "prédicteur aviator"],
  ko: ["주사위 전략", "마인즈 전략", "크래시 예측", "축구 베팅", "키노 팁", "룰렛 전략", "블랙잭 팁", "플링코 전략", "에이비에이터 예측"],
  tr: ["dice strateji", "mayın strateji", "crash tahminci", "futbol bahis", "keno ipuçları", "rulet strateji", "blackjack ipuçları", "plinko strateji", "aviator tahminci"],
  vi: ["chiến lược xúc xắc", "chiến lược mìn", "dự đoán crash", "cá cược bóng đá", "keno mẹo", "chiến lược roulette", "blackjack mẹo", "chiến lược plinko", "dự đoán aviator"],
  it: ["strategia dadi", "strategia mine", "predictor crash", "scommesse calcio", "keno consigli", "strategia roulette", "blackjack consigli", "strategia plinko", "predictor aviator"],
  nl: ["dobbelsteen strategie", "mijnen strategie", "crash predictor", "voetbal weddenschappen", "keno tips", "roulette strategie", "blackjack tips", "plinko strategie", "aviator predictor"],
  pl: ["strategia kości", "strategia miny", "predyktor crash", "zakłady piłka nożna", "keno wskazówki", "strategia ruletka", "blackjack wskazówki", "strategia plinko", "predyktor aviator"],
  id: ["strategi dadu", "strategi mines", "prediktor crash", "taruhan sepak bola", "keno tips", "strategi roulette", "blackjack tips", "strategi plinko", "prediktor aviator"],
  th: ["กลยุทธ์ลูกเต๋า", "กลยุทธ์ mines", "ทำนาย crash", "เดิมพันฟุตบอล", "คีโนเคล็ดลับ", "กลยุทธ์รูเล็ต", "แบล็คแจ็คเคล็ดลับ", "plinko กลยุทธ์", "ทำนาย aviator"],
  bn: ["পাশা কৌশল", "মাইনস কৌশল", "ক্র্যাশ ভবিষ্যদ্বাণী", "ফুটবল বেটিং", "কেনো টিপস", "রুলেট কৌশল", "ব্ল্যাকজ্যাক টিপস", "প্লিংকো কৌশল", "এভিয়েটর ভবিষ্যদ্বাণী"],
  ms: ["strategi dadu", "strategi mines", "peramal crash", "pertaruhan bola sepak", "keno tips", "strategi roulette", "blackjack tips", "strategi plinko", "peramal aviator"],
};

/** Per-locale keyword sets – top search terms in that language */
const LOCALE_KEYWORDS: Record<Locale, string[]> = {
  en: [...EN_BASE, ...EN_DICE, ...EN_SPORTS_ALL, ...EN_GAMES_OTHER, ...EN_GUIDES, ...EN_PROVIDERS, ...EN_BEST_WIN, ...EN_DOWNLOAD, ...EN_EXTRA, ...LOCALE_NATIVE.en, ...TYPO_KEYWORDS],
  zh: [
    "Stake 策略",
    "Roobet 策略",
    "扫雷策略",
    "骰子策略",
    "crash 预测",
    "加密货币赌场",
    "体育博彩",
    "足球预测",
    "篮球预测",
    "比赛预测",
    "1xbet 策略",
    "下载博彩工具",
    ...LOCALE_EXTRA.zh,
    ...LOCALE_NATIVE.zh,
    ...EN_BASE.slice(0, 15),
    ...EN_DICE.slice(0, 20),
    ...EN_SPORTS_ALL.slice(0, 25),
    ...EN_GAMES_OTHER.slice(0, 22),
    ...EN_GUIDES.slice(0, 14),
    ...EN_PROVIDERS.slice(0, 18),
    ...EN_BEST_WIN.slice(0, 18),
    ...EN_DOWNLOAD.slice(0, 14),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 18),
  ],
  es: [
    "estrategia Stake",
    "predictor Roobet",
    "estrategia minas",
    "estrategia dados",
    "predictor crash",
    "casino cripto",
    "apuestas deportivas",
    "predicción partidos",
    "fútbol apuestas",
    "descargar herramientas apuestas",
    ...LOCALE_EXTRA.es,
    ...LOCALE_NATIVE.es,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  hi: [
    "Stake रणनीति",
    "Roobet रणनीति",
    "क्रिप्टो कैसीनो",
    "स्पोर्ट्स बेटिंग",
    "फुटबॉल भविष्यवाणी",
    "मैच भविष्यवाणी",
    ...LOCALE_EXTRA.hi,
    ...LOCALE_NATIVE.hi,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  ar: [
    "استراتيجية Stake",
    "متنبئ Roobet",
    "كازينو كريبتو",
    "مراهنات رياضية",
    "تنبؤ المباريات",
    "كرة القدم مراهنات",
    ...LOCALE_EXTRA.ar,
    ...LOCALE_NATIVE.ar,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  pt: [
    "estratégia Stake",
    "predictor Roobet",
    "estratégia minas",
    "estratégia dados",
    "casino cripto",
    "apostas desportivas",
    "previsão de jogos",
    "futebol apostas",
    "descarregar ferramentas apostas",
    ...LOCALE_EXTRA.pt,
    ...LOCALE_NATIVE.pt,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  ru: [
    "стратегия Stake",
    "предиктор Roobet",
    "крипто казино",
    "спортивные ставки",
    "прогноз матчей",
    "ставки на футбол",
    ...LOCALE_EXTRA.ru,
    ...LOCALE_NATIVE.ru,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  ja: [
    "Stake 戦略",
    "Roobet 予測",
    "ダイス戦略",
    "クラッシュ予測",
    "暗号カジノ",
    "スポーツベッティング",
    "試合予測",
    "サッカー予測",
    ...LOCALE_EXTRA.ja,
    ...LOCALE_NATIVE.ja,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  de: [
    "Stake Strategie",
    "Roobet Predictor",
    "Krypto Casino Strategie",
    "Würfel Strategie",
    "Sportwetten Tipps",
    "Spielvorhersage",
    "Fußball Wetten",
    "Wett-Tools herunterladen",
    ...LOCALE_EXTRA.de,
    ...LOCALE_NATIVE.de,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  fr: [
    "stratégie Stake",
    "prédicteur Roobet",
    "stratégie mines",
    "stratégie dés",
    "casino crypto",
    "paris sportifs",
    "prédiction match",
    "paris football",
    "télécharger outils paris",
    ...LOCALE_EXTRA.fr,
    ...LOCALE_NATIVE.fr,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  ko: [
    "Stake 전략",
    "Roobet 예측",
    "크래시 예측",
    "주사위 전략",
    "암호화폐 카지노",
    "스포츠 베팅",
    "경기 예측",
    "축구 베팅",
    ...LOCALE_EXTRA.ko,
    ...LOCALE_NATIVE.ko,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  tr: [
    "Stake strateji",
    "Roobet tahminci",
    "kripto casino",
    "spor bahisleri",
    "maç tahmini",
    "dice strateji",
    "futbol bahis",
    ...LOCALE_EXTRA.tr,
    ...LOCALE_NATIVE.tr,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  vi: [
    "chiến lược Stake",
    "dự đoán Roobet",
    "casino crypto",
    "cá cược thể thao",
    "dự đoán trận đấu",
    "xúc xắc chiến lược",
    "bóng đá cá cược",
    ...LOCALE_EXTRA.vi,
    ...LOCALE_NATIVE.vi,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  it: [
    "strategia Stake",
    "predictor Roobet",
    "casino crypto",
    "strategia dadi",
    "scommesse sportive",
    "previsione partite",
    "scommesse calcio",
    ...LOCALE_EXTRA.it,
    ...LOCALE_NATIVE.it,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  nl: [
    "Stake strategie",
    "Roobet predictor",
    "crypto casino",
    "dobbelsteen strategie",
    "sportweddenschappen",
    "wedstrijdvoorspelling",
    "voetbal weddenschappen",
    ...LOCALE_EXTRA.nl,
    ...LOCALE_NATIVE.nl,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  pl: [
    "strategia Stake",
    "predyktor Roobet",
    "kasyno krypto",
    "strategia kości",
    "zakłady sportowe",
    "predykcja meczu",
    "zakłady piłka nożna",
    ...LOCALE_EXTRA.pl,
    ...LOCALE_NATIVE.pl,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  id: [
    "strategi Stake",
    "prediktor Roobet",
    "casino kripto",
    "strategi dadu",
    "taruhan olahraga",
    "prediksi pertandingan",
    "taruhan sepak bola",
    ...LOCALE_EXTRA.id,
    ...LOCALE_NATIVE.id,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  th: [
    "กลยุทธ์ Stake",
    "Roobet ทำนาย",
    "คาสิโนคริปโต",
    "กลยุทธ์ลูกเต๋า",
    "การเดิมพันกีฬา",
    "ทำนายแมตช์",
    "ทำนายฟุตบอล",
    ...LOCALE_EXTRA.th,
    ...LOCALE_NATIVE.th,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  bn: [
    "Stake কৌশল",
    "Roobet ভবিষ্যদ্বাণী",
    "ক্রিপ্টো ক্যাসিনো",
    "পাশা কৌশল",
    "খেলাধুলা বেটিং",
    "ফুটবল ভবিষ্যদ্বাণী",
    ...LOCALE_EXTRA.bn,
    ...LOCALE_NATIVE.bn,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_PROVIDERS.slice(0, 15),
    ...EN_BEST_WIN.slice(0, 15),
    ...EN_DOWNLOAD.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
  ms: [
    "strategi Stake",
    "peramal Roobet",
    "kasino kripto",
    "strategi dadu",
    "pertaruhan sukan",
    "ramalan perlawanan",
    "pertaruhan bola sepak",
    ...LOCALE_EXTRA.ms,
    ...LOCALE_NATIVE.ms,
    ...EN_BASE.slice(0, 12),
    ...EN_DICE.slice(0, 18),
    ...EN_SPORTS_ALL.slice(0, 22),
    ...EN_GAMES_OTHER.slice(0, 20),
    ...EN_GUIDES.slice(0, 12),
    ...EN_EXTRA.slice(0, 8),
    ...TYPO_KEYWORDS.slice(0, 16),
  ],
};

/** Sport name variants for matching EN_SPORTS_ALL (slug/name -> search substring) */
const SPORT_MATCH_TERMS: Record<string, string[]> = {
  football: ["football"],
  soccer: ["soccer", "football"],
  basketball: ["basketball", "NBA"],
  tennis: ["tennis"],
  cricket: ["cricket"],
  esports: ["esports", "CSGO", "Dota", "League of Legends", "LoL"],
  ufc: ["UFC"],
  boxing: ["boxing"],
  "horse-racing": ["horse racing"],
  "american-football": ["American football", "NFL"],
  "ice-hockey": ["ice hockey", "hockey"],
  baseball: ["baseball", "MLB"],
  mma: ["MMA"],
  csgo: ["CSGO"],
  dota: ["Dota"],
  lol: ["League of Legends", "LoL"],
};

/** Sport-specific keywords – in page language + full EN_SPORTS_ALL for that sport + locale base */
export function getSportKeywords(sportSlug: string, locale: Locale): string[] {
  const sport = SPORTS.find((s) => s.slug === sportSlug);
  const name = sport?.name ?? sportSlug;
  const stems = LOCALE_STEMS[locale] ?? LOCALE_STEMS.en;
  const inLocale = [
    `${name} ${stems.betting} ${stems.tips}`,
    `${name} ${stems.matchPrediction}`,
    `${name} ${stems.strategy}`,
    `${stems.betting} ${name}`,
  ];
  const baseEn = [
    `${name} betting tips`,
    `${name} match prediction`,
    `${name} strategy`,
    `sports betting ${name}`,
    `download ${name} betting tools`,
    "Stake sports",
    "Roobet sports",
    "1xbet sports",
  ];
  const matchTerms = SPORT_MATCH_TERMS[sportSlug];
  const fromSportsAll = matchTerms
    ? EN_SPORTS_ALL.filter((phrase) =>
        matchTerms.some((t) => phrase.toLowerCase().includes(t.toLowerCase()))
      )
    : [];
  return [...inLocale, ...baseEn, ...fromSportsAll, ...(LOCALE_KEYWORDS[locale] ?? LOCALE_KEYWORDS.en).slice(0, 12)];
}

/** Meta keywords for a page – heavy rank level, all types (casino+game+strategy/predictor, sport, etc.) in page language + typos */
export function getMetaKeywords(
  locale: Locale,
  options?: {
    casino?: string;
    game?: string;
    sport?: string;
    includeTypos?: boolean;
  }
): string[] {
  const list = [...(LOCALE_KEYWORDS[locale] ?? LOCALE_KEYWORDS.en)];
  const stems = LOCALE_STEMS[locale] ?? LOCALE_STEMS.en;
  if (options?.casino) {
    const c = options.casino;
    list.unshift(
      `${c} ${stems.strategy}`,
      `${c} ${stems.predictor}`,
      `${c} ${stems.tips}`,
      `${c} mines ${stems.strategy}`,
      `${c} crash ${stems.predictor}`
    );
  }
  if (options?.game) {
    const g = options.game;
    list.unshift(
      `${g} ${stems.strategy}`,
      `${g} ${stems.predictor}`,
      `${g} ${stems.tips}`
    );
  }
  if (options?.sport) {
    const s = options.sport;
    list.unshift(
      `${s} ${stems.betting}`,
      `${s} ${stems.matchPrediction}`,
      `${s} ${stems.tips}`
    );
  }
  if (options?.includeTypos !== false) {
    list.push(...TYPO_KEYWORDS.slice(0, 15));
  }
  return Array.from(new Set(list)).slice(0, 80);
}

/** Default meta keywords for locale (home, strategies list) */
export function getDefaultMetaKeywords(locale: Locale): string[] {
  return getMetaKeywords(locale, { includeTypos: true });
}
